<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
  <link href="/assets/css/style.css" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/monokai.min.css">
  <link rel="apple-touch-icon" href="icon.png">
  <meta name="theme-color" content="#fafafa">
  <link href="https://fonts.googleapis.com/css?family=Asap" rel="stylesheet">
  <!-- Begin Jekyll SEO tag v2.8.0 -->
<title>ActiveJob::Exceptions::ClassMethods | RailsDoc(β)</title>
<meta name="generator" content="Jekyll v3.9.2" />
<meta property="og:title" content="ActiveJob::Exceptions::ClassMethods" />
<meta property="og:locale" content="en_US" />
<meta name="description" content="Ruby on Rails API Documentation." />
<meta property="og:description" content="Ruby on Rails API Documentation." />
<link rel="canonical" href="https://railsdoc.github.io/5.2/classes/ActiveJob/Exceptions/ClassMethods.html" />
<meta property="og:url" content="https://railsdoc.github.io/5.2/classes/ActiveJob/Exceptions/ClassMethods.html" />
<meta property="og:site_name" content="RailsDoc(β)" />
<meta property="og:image" content="https://avatars.githubusercontent.com/u/4223" />
<meta property="og:type" content="website" />
<meta name="twitter:card" content="summary" />
<meta property="twitter:image" content="https://avatars.githubusercontent.com/u/4223" />
<meta property="twitter:title" content="ActiveJob::Exceptions::ClassMethods" />
<meta name="twitter:site" content="@" />
<script type="application/ld+json">
{"@context":"https://schema.org","@type":"WebPage","description":"Ruby on Rails API Documentation.","headline":"ActiveJob::Exceptions::ClassMethods","image":"https://avatars.githubusercontent.com/u/4223","url":"https://railsdoc.github.io/5.2/classes/ActiveJob/Exceptions/ClassMethods.html"}</script>
<!-- End Jekyll SEO tag -->

  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-134470810-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag() { dataLayer.push(arguments); }
    gtag('js', new Date());

    gtag('config', 'UA-134470810-1');

    window.config = {
      rootPath: "/5.2/"
    }
  </script>
</head>
<body>
  <header class="navbar navbar-dark navbar-expand bg-dark flex-md-nowrap p-0 shadow sticky-header">
    <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="/">RailsDoc(β)</a>
    <form class="w-100 d-none d-md-flex" action="/search" method="get">
      <input id="search-form" class="form-control form-control-dark" type="text" placeholder="Search" aria-label="Search" name="q">
    </form>

    <ul class="navbar-nav flex-row ml-md-auto d-none d-md-flex px-1">
      <li class="nav-item text-nowrap p-1">
        <div class="dropdown">
          <a class="dropdown-toggle nav-link" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            v5.2
          </a>
          <div class="dropdown-menu dropdown-menu-md-right" aria-labelledby="dropdownMenuLink">
            <a class="dropdown-item" href="/">v7.0</a>
            
              
              <a class="dropdown-item" href="/6.1/">v6.1</a>
            
              
              <a class="dropdown-item" href="/6.0/">v6.0</a>
            
              
              <a class="dropdown-item" href="/5.2/">v5.2</a>
            
          </div>
        </div>
      </li>
      <li class="nav-item text-nowrap p-1">
        <a class="nav-link p-2" href="https://github.com/railsdoc/railsdoc.github.io">GitHub</a>
      </li>
    </ul>
  </header>

  <div class="container-fluid">
    <div class="row">
      <nav class="col-12 col-md-3 col-xl-2 d-none d-md-block bg-light sidebar-sticky">
        <div id="navigation" class="sidebar-content">
        </div>
      </nav>

      <div class="col-12 col-md-3 col-xl-2 toc-content-sticky">
        <div class="toc-content"><ul id="toc" class="section-nav">
<li class="toc-entry toc-h2"><a href="#methods">Methods</a></li>
<li class="toc-entry toc-h2"><a href="#instance-public-methods">Instance Public methods</a>
<ul>
<li class="toc-entry toc-h3"><a href="#method-i-discard_on">
            
              discard_on(exception)
            
          </a></li>
<li class="toc-entry toc-h3"><a href="#method-i-retry_on">
            
              retry_on(exception, wait: 3.seconds, attempts: 5, queue: nil, priority: nil)
            
          </a></li>
</ul>
</li>
</ul></div>
      </div>

      <main role="main" class="col-12 col-md-9 col-xl-8 py-md-3 pl-md-4">
        <div class="main">
    <div class="banner">
        
            <span>Ruby on Rails 5.2.8</span><br />
        
        <div class="type">Module</div>
        <h1>
            ActiveJob::Exceptions::ClassMethods
            
        </h1>
        <ul class="files">
            
            <li><a href="../../../files/activejob/lib/active_job/exceptions_rb.html">activejob/lib/active_job/exceptions.rb</a></li>
            
        </ul>
    </div>
    <div id="bodyContent">
        <div id="content">
  

  

  
  


  

  
    <h2 id="methods">Methods</h2>
    <ul>
      
        <li>
          <a href="#method-i-discard_on">discard_on</a>
        </li>
      
        <li>
          <a href="#method-i-retry_on">retry_on</a>
        </li>
      
    </ul>
  

  

  
    

    

    

    

    <!-- Methods -->
    
    
      <h2 id="instance-public-methods">Instance Public methods</h2>
      
        <div class="method">
          <h3 id="method-i-discard_on">
            
              discard_on(exception)
            
          </h3>

          
            <div class="description">
              <p>Discard the job with no attempts to retry, if the exception is raised. This is useful when the subject of the job, like an Active Record, is no longer available, and the job is thus no longer relevant.</p>

<p>You can also pass a block that&#39;ll be invoked. This block is yielded with the job instance as the first and the error instance as the second parameter.</p>

<h4 id="method-i-discard_on-label-Example">Example</h4>

<pre><code>class SearchIndexingJob &lt; ActiveJob::Base
  discard_on ActiveJob::DeserializationError
  discard_on(CustomAppException) do |job, error|
    ExceptionNotifier.caught(error)
  end

  def perform(record)
    # Will raise ActiveJob::DeserializationError if the record can&#39;t be deserialized
    # Might raise CustomAppException for something domain specific
  end
end
</code></pre>
            </div>
          

          

          

          
            
            <div class="sourcecode">
              
              <p class="source-link">
                Source:
                
              </p>
              <div id="method-i-discard_on_source">
                <pre><code class="ruby"><span class="ruby-comment"># File activejob/lib/active_job/exceptions.rb, line 79</span>
<span class="ruby-keyword">def</span> <span class="ruby-identifier ruby-title">discard_on</span>(<span class="ruby-identifier">exception</span>)
  <span class="ruby-identifier">rescue_from</span> <span class="ruby-identifier">exception</span> <span class="ruby-keyword">do</span> <span class="ruby-operator">|</span><span class="ruby-identifier">error</span><span class="ruby-operator">|</span>
    <span class="ruby-keyword">if</span> <span class="ruby-identifier">block_given?</span>
      <span class="ruby-keyword">yield</span> <span class="ruby-keyword">self</span>, <span class="ruby-identifier">error</span>
    <span class="ruby-keyword">else</span>
      <span class="ruby-identifier">logger</span>.<span class="ruby-identifier">error</span> <span class="ruby-node">&quot;Discarded #{self.class} due to a #{exception}. The original exception was #{error.cause.inspect}.&quot;</span>
    <span class="ruby-keyword">end</span>
  <span class="ruby-keyword">end</span>
<span class="ruby-keyword">end</span></code></pre>
              </div>
            </div>
            
          </div>
        
        <div class="method">
          <h3 id="method-i-retry_on">
            
              retry_on(exception, wait: 3.seconds, attempts: 5, queue: nil, priority: nil)
            
          </h3>

          
            <div class="description">
              <p>Catch the exception and reschedule job for re-execution after so many seconds, for a specific number of attempts. If the exception keeps getting raised beyond the specified number of attempts, the exception is allowed to bubble up to the underlying queuing system, which may have its own retry mechanism or place it in a holding queue for inspection.</p>

<p>You can also pass a block that&#39;ll be invoked if the retry attempts fail for custom logic rather than letting the exception bubble up. This block is yielded with the job instance as the first and the error instance as the second parameter.</p>

<h4 id="method-i-retry_on-label-Options">Options</h4>
<ul><li>
<p><code>:wait</code> - Re-enqueues the job with a delay specified either in seconds (default: 3 seconds), as a computing proc that the number of executions so far as an argument, or as a symbol reference of <code>:exponentially_longer</code>, which applies the wait algorithm of <code>(executions ** 4) + 2</code> (first wait 3s, then 18s, then 83s, etc)</p>
</li><li>
<p><code>:attempts</code> - Re-enqueues the job the specified number of times (default: 5 attempts)</p>
</li><li>
<p><code>:queue</code> - Re-enqueues the job on a different queue</p>
</li><li>
<p><code>:priority</code> - Re-enqueues the job with a different priority</p>
</li></ul>

<h4 id="method-i-retry_on-label-Examples">Examples</h4>

<pre><code>class RemoteServiceJob &lt; ActiveJob::Base
  retry_on CustomAppException # defaults to 3s wait, 5 attempts
  retry_on AnotherCustomAppException, wait: -&gt;(executions) { executions * 2 }
  retry_on(YetAnotherCustomAppException) do |job, error|
    ExceptionNotifier.caught(error)
  end
  retry_on ActiveRecord::Deadlocked, wait: 5.seconds, attempts: 3
  retry_on Net::OpenTimeout, wait: :exponentially_longer, attempts: 10

  def perform(*args)
    # Might raise CustomAppException, AnotherCustomAppException, or YetAnotherCustomAppException for something domain specific
    # Might raise ActiveRecord::Deadlocked when a local db deadlock is detected
    # Might raise Net::OpenTimeout when the remote service is down
  end
end
</code></pre>
            </div>
          

          

          

          
            
            <div class="sourcecode">
              
              <p class="source-link">
                Source:
                
              </p>
              <div id="method-i-retry_on_source">
                <pre><code class="ruby"><span class="ruby-comment"># File activejob/lib/active_job/exceptions.rb, line 45</span>
<span class="ruby-keyword">def</span> <span class="ruby-identifier ruby-title">retry_on</span>(<span class="ruby-identifier">exception</span>, <span class="ruby-value">wait:</span> <span class="ruby-value">3</span>.<span class="ruby-identifier">seconds</span>, <span class="ruby-value">attempts:</span> <span class="ruby-value">5</span>, <span class="ruby-value">queue:</span> <span class="ruby-keyword">nil</span>, <span class="ruby-value">priority:</span> <span class="ruby-keyword">nil</span>)
  <span class="ruby-identifier">rescue_from</span> <span class="ruby-identifier">exception</span> <span class="ruby-keyword">do</span> <span class="ruby-operator">|</span><span class="ruby-identifier">error</span><span class="ruby-operator">|</span>
    <span class="ruby-keyword">if</span> <span class="ruby-identifier">executions</span> <span class="ruby-operator">&lt;</span> <span class="ruby-identifier">attempts</span>
      <span class="ruby-identifier">logger</span>.<span class="ruby-identifier">error</span> <span class="ruby-node">&quot;Retrying #{self.class} in #{wait} seconds, due to a #{exception}. The original exception was #{error.cause.inspect}.&quot;</span>
      <span class="ruby-identifier">retry_job</span> <span class="ruby-value">wait:</span> <span class="ruby-identifier">determine_delay</span>(<span class="ruby-identifier">wait</span>), <span class="ruby-value">queue:</span> <span class="ruby-identifier">queue</span>, <span class="ruby-value">priority:</span> <span class="ruby-identifier">priority</span>
    <span class="ruby-keyword">else</span>
      <span class="ruby-keyword">if</span> <span class="ruby-identifier">block_given?</span>
        <span class="ruby-keyword">yield</span> <span class="ruby-keyword">self</span>, <span class="ruby-identifier">error</span>
      <span class="ruby-keyword">else</span>
        <span class="ruby-identifier">logger</span>.<span class="ruby-identifier">error</span> <span class="ruby-node">&quot;Stopped retrying #{self.class} due to a #{exception}, which reoccurred on #{executions} attempts. The original exception was #{error.cause.inspect}.&quot;</span>
        <span class="ruby-identifier">raise</span> <span class="ruby-identifier">error</span>
      <span class="ruby-keyword">end</span>
    <span class="ruby-keyword">end</span>
  <span class="ruby-keyword">end</span>
<span class="ruby-keyword">end</span></code></pre>
              </div>
            </div>
            
          </div>
        
      
    
  
</div>

    </div>
</div>

        <footer class="site-footer">
          <!-- <span class="site-footer-credits">This page was generated by <a href="https://pages.github.com">GitHub Pages</a>.</span> -->
        </footer>
      </main>
    </div>
  </div>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/anchor-js/4.3.0/anchor.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/highlight.min.js"></script>
  <script src="/assets/js/app.js"></script>
  <script src="/assets/js/search.js"></script>
</body>
</html>
